# If you are building on a linux-based system, and if you have the
# make-installer.sh script installed (from https://github.com/scorbo2/install-scripts),
# this this config will be used to autogenerate an installer tarball for your application.
# This is already wired up in the supplied pom.xml file, so it will run on every maven build.
#
# ALL PATHS ARE RELATIVE TO PROJECT ROOT

# Currently we are limited to "tarball" (.tar.gz) generation.
# In future, may support RPM or DEB package generation.
FORMAT="tarball"

APPLICATION="CryptText"
VERSION="1.0"

CATEGORY="TextEditor"

PROJECT_URL="https://github.com/scorbo2/crypttext"

# Extra memory settings like Xmx and Xms can be specified here:
JAVAMEM=

JAR="target/crypttext-${VERSION}.jar"
OUTPUT_DIR=target

# Space-separated list of files and dirs to include:
TO_COPY="target/lib"
TO_COPY="${TO_COPY} src/main/resources/ca/corbett/crypttext/ReleaseNotes.txt"

# TODO CryptText v1 has no external application extensions yet... uncomment this later
#TO_COPY="${TO_COPY} update_sources.json"

TO_COPY="${TO_COPY} src/main/resources/ca/corbett/crypttext/images/logo.png"
